### ISSUE TITLE
`colstart` is not correct

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_CircuitPython_SSD1680#5] opened 2021-08-27 14:14 UTC
With the [Adafruit 2.13" HD Tri-Color eInk / ePaper Display FeatherWing](https://www.adafruit.com/product/4814) the default `colstart` value passed to the `displayio.EPaperDisplay` constructor is wrong
https://github.com/adafruit/Adafruit_CircuitPython_SSD1680/blob/eefe74c3b33189ba475e01bbee774a931392898a/adafruit_ssd1680.py#L82-L100

Using the `simpletest` example with the included `display-ruler.bmp` I get the following with lines of noise at the bottom and lines missing from the top:
![SSD1680_default_colstart](https://user-images.githubusercontent.com/70200140/131139749-4de3b4d6-3b8a-460f-a5b1-2197f6e0c208.jpg)

If I change the `colstart` in the library to `8` it lines up correctly:
![SSD1680_colstart_8](https://user-images.githubusercontent.com/70200140/131139903-fe8d554b-5cc0-4a81-8baa-c836f6e3d78f.jpg)

Do the other Adafruit products that uses the SSD1680 library work with default `colstart` value or do they all suffer from this noise?

I can either do a PR to:
- change the default value to `8`
- expose `colstart` as a `SSD1680` constructor parameter and add constants and documentation

Could someone with access to the other displays report back on their behaviour please?

**Comment by Neradoc** [comment] 2022-08-09 17:43
Somebody on discord ran into that issue too, setting colstart to 8 worked. With this wing:
[Adafruit 2.13" Monochrome eInk / ePaper Display FeatherWing - 250x122 Monochrome with SSD1680](https://www.adafruit.com/product/4195)
I don't have the hardware to properly test this. So, to whoever knows about the hardware:
- is it common to all such displays ?
- or is it a case of different models needing a different setup ?
- if so, can the hardware be detected in the code or should there be variants in the library ?

**Comment by jposada202020** [comment] 2023-02-18 19:42
I have tested this in the following products
* `Adafruit 2.13" Tri-Color eInk Display FeatherWing 
* `Adafruit 2.13" Mono eInk Display FeatherWing 

In both cases problem is solved when using colstart=8 as per example in #9 . However, did not test on 
* `Adafruit 2.13" Tri-Color eInk Display Breakout

So maybe for this particular case colstart=8 would not work

**Comment by dave-ct** [comment] 2023-02-18 20:26
Just have the same two featherwings also.

**Comment by jposada202020** [comment] 2023-02-21 16:13
Thanks dave-ct. Hopefully I can test over the weeeknd. Thanks again for your help dave

**Comment by tannewt** [comment] 2023-02-21 17:29
Note, I don't expect the default to always be right because multiple displays use the same driver IC in different configurations. I'd expect to have a simpletest for each product that would include the correct colstart.

**Comment by makermelissa** [comment] 2023-02-21 17:32
> I can either do a PR to:
> 
> * change the default value to `8`
> * expose `colstart` as a `SSD1680` constructor parameter and add constants and documentation

This may have been caused by #9, which was an attempt to fix #10 by doing the second item on the list. 

> I have tested this in the following products
> 
> * `Adafruit 2.13" Tri-Color eInk Display FeatherWing
> * `Adafruit 2.13" Mono eInk Display FeatherWing
> 
> In both cases problem is solved when using colstart=8 as per example in #9 . However, did not test on
> 
> * `Adafruit 2.13" Tri-Color eInk Display Breakout
> 
> So maybe for this particular case colstart=8 would not work
> 
> @dave-ct just pinging you in case you own an Adafruit #4947 Display

Keep in mind that there are older and newer versions of both the tri-color and monochrome 2.13" Displays. Newer displays use the SSD1680, the older monochrome uses the SSD1675 driver, and the older tri-color uses the ILI0373. Sometimes the older displays almost work using the wrong driver, which may have been the case with #9. So we just want to be sure the display that is being tested is in fact the newer one. If unlabeled, I usually tell these apart by comparing the tabs on the left side of the display and comparing to product photos.

Apparently it's been a non-settable 1 since I first wrote the driver. I'm not sure why it's suddenly shifted. I don't think there was any change to the displays themselves. Maybe an internal change in CircuitPython did something. It may be worth testing against an older build as well.

> Note, I don't expect the default to always be right because multiple displays use the same driver IC in different configurations. I'd expect to have a simpletest for each product that would include the correct colstart.

Good point. We should probably just leave it 1 for now and just update the examples as needed.

**Comment by jposada202020** [comment] 2023-02-21 18:32
Got it, I do have some SSD1680 and some SSD1675, ill take a look over the weekend and make the Pr for the examples. Thanks :)

**Comment by makermelissa** [comment] 2023-02-21 19:05
Thanks. SSD1675 should use https://github.com/adafruit/Adafruit_CircuitPython_SSD1675

**Comment by jposada202020** [comment] 2023-02-24 00:22
Some news, I tested on the `Adafruit 2.13" Tri-Color eInk Display Breakout` and the colstart=8 is indeed the correct values, showing that all three screens for the `SSD1680` Adafruit family are good to go. Will submit a PR for a new example and with that close this issue. Next step the `SSD1675`

**Closed** 2023-02-28 00:08 UTC
